Models/Terms.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Clinic.Models
{
    public class Terms
    {
        [Key]
        public int TermID
        {get; set; }

        [Required]
        [StringLength(100)]
        public string Category
        {get;set;}

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date")]
        public DateTime Date { get; set; }

        [Display(Name = "Priority")]
        public bool Priority { get; set; }

        [Display(Name = "Doctor")]
        public int? DoctorId
        { get;set;}


        [Display(Name = "Doctor")]
        public Doctors Doctor
        { get; set; }
        
        public ICollection<Scheduling> Patients
        {get;set;}
    }
}

Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clinic.Data;
using Clinic.Models;

namespace Clinic.Controllers
{
    public class DoctorsController : Controller
    {
        private readonly ClinicContext _context;

        public DoctorsController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Doctors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Doctors.ToListAsync());
        }

        // GET: Doctors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctors = await _context.Doctors
                .FirstOrDefaultAsync(m => m.DoctorId == id);
            if (doctors == null)
            {
                return NotFound();
            }

            return View(doctors);
        }

        // GET: Doctors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DoctorId,FirstName,LastName,Degree,OfficeNumber,HireDate")] Doctors doctors)
        {
            if (ModelState.IsValid)
            {
                _context.Add(doctors);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doctors);
        }

        // GET: Doctors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctors = await _context.Doctors.FindAsync(id);
            if (doctors == null)
            {
                return NotFound();
            }
            return View(doctors);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DoctorId,FirstName,LastName,Degree,OfficeNumber,HireDate")] Doctors doctors)
        {
            if (id != doctors.DoctorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doctors);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoctorsExists(doctors.DoctorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doctors);
        }

        // GET: Doctors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doctors = await _context.Doctors
                .FirstOrDefaultAsync(m => m.DoctorId == id);
            if (doctors == null)
            {
                return NotFound();
            }

            return View(doctors);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doctors = await _context.Doctors.FindAsync(id);
            _context.Doctors.Remove(doctors);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoctorsExists(int id)
        {
            return _context.Doctors.Any(e => e.DoctorId == id);
        }
    }
}

Controllers/PatientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clinic.Data;
using Clinic.Models;

namespace Clinic.Controllers
{
    public class PatientsController : Controller
    {
        private readonly ClinicContext _context;

        public PatientsController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Patients
        public async Task<IActionResult> Index()
        {
            return View(await _context.Patients.ToListAsync());
        }

        // GET: Patients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patients = await _context.Patients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patients == null)
            {
                return NotFound();
            }

            return View(patients);
        }

        // GET: Patients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PatientId,FirstName,LastName,ScheduledDate,HealthInsurance")] Patients patients)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patients);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(patients);
        }

        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patients = await _context.Patients.FindAsync(id);
            if (patients == null)
            {
                return NotFound();
            }
            return View(patients);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PatientId,FirstName,LastName,ScheduledDate,HealthInsurance")] Patients patients)
        {
            if (id != patients.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patients);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientsExists(patients.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patients);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patients = await _context.Patients
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patients == null)
            {
                return NotFound();
            }

            return View(patients);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patients = await _context.Patients.FindAsync(id);
            _context.Patients.Remove(patients);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientsExists(int id)
        {
            return _context.Patients.Any(e => e.Id == id);
        }
    }
}

Controllers/TermsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clinic.Data;
using Clinic.Models;
using Clinic.ViewModels;

namespace Clinic.Controllers
{
    public class TermsController : Controller
    {
        private readonly ClinicContext _context;

        public TermsController(ClinicContext context)
        {
            _context = context;
        }

        // GET: Terms
        public async Task<IActionResult> Index(bool termPriority, string searchString)
        {
            IQueryable<Terms> terms = _context.Terms.AsQueryable();
            IQueryable<bool> priorityQuery = _context.Terms.OrderBy(m => m.Priority).Select(m => m.Priority).Distinct();
            if (!string.IsNullOrEmpty(searchString))
            {
                terms = terms.Where(s => s.Category.Contains(searchString));
            }
            if (termPriority==true)
            {
                terms = terms.Where(x => x.Priority == termPriority);
            }
            terms = terms.Include(m => m.Doctor)
            .Include(m => m.Patients).ThenInclude(m => m.Patient);
            var termPriorityVM = new TermPriorityViewModel
            {
                Priorities = new SelectList(await priorityQuery.ToListAsync()),
                Terms = await terms.ToListAsync()
            };
            return View(termPriorityVM);
        }

        // GET: Terms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terms = await _context.Terms
                .Include(t => t.Doctor)
                .Include(m => m.Patients).ThenInclude(m => m.Patient)
                .FirstOrDefaultAsync(m => m.TermID == id);
            if (terms == null)
            {
                return NotFound();
            }

            return View(terms);
        }

        // GET: Terms/Create
        public IActionResult Create()
        {
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", "FullName");
            return View();
        }

        // POST: Terms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TermID,Category,Date,Priority,DoctorId")] Terms terms)
        {
            if (ModelState.IsValid)
            {
                _context.Add(terms);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", "FullName", terms.DoctorId);
            return View(terms);
        }

        // GET: Terms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terms = _context.Terms.Where(m => m.TermID == id).Include(m => m.Patients).First();
            if (terms == null)
            {
                return NotFound();
            }
            TermPatientEditViewModel viewmodel = new TermPatientEditViewModel
            {
                Term = terms,
                PatientList = new MultiSelectList(_context.Patients.OrderBy(s => s.FullName), "Id", "FullName"),
                SelectedPatients = terms.Patients.Select(sa => sa.PatientID)
            };
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", "FullName", terms.DoctorId);
            return View(viewmodel);
        }

        // POST: Terms/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TermPatientEditViewModel viewmodel)
        {
            if (id != viewmodel.Term.TermID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                     
                        _context.Update(viewmodel.Term);
                        await _context.SaveChangesAsync();
                        IEnumerable<int> listPatients = viewmodel.SelectedPatients;
                        IQueryable<PatientTerm> toBeRemoved = _context.PatientTerm.Where(s => !listPatients.Contains(s.PatientId) && s.TermId == id);
                        _context.PatientTerm.RemoveRange(toBeRemoved);
                        IEnumerable<int> existPatients = _context.PatientTerm.Where(s => listPatients.Contains(s.PatientId) && s.TermId == id).Select(s => s.PatientId);
                        IEnumerable<int> newPatients = listPatients.Where(s => !existPatients.Contains(s));
                        foreach (int patientId in newPatients)
                            _context.PatientTerm.Add(new PatientTerm { PatientId = patientId, TermId = id });
                    }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TermsExists(viewmodel.Term.TermID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DoctorId"] = new SelectList(_context.Doctors, "DoctorId", "FullName", viewmodel.Term.DoctorId);
            return View(viewmodel);
        }

        // GET: Terms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var terms = await _context.Terms
                .Include(t => t.Doctor)
                .Include(m => m.Patients).ThenInclude(m => m.Patient)
                .FirstOrDefaultAsync(m => m.TermID == id);
            if (terms == null)
            {
                return NotFound();
            }

            return View(terms);
        }

        // POST: Terms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var terms = await _context.Terms.FindAsync(id);
            _context.Terms.Remove(terms);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TermsExists(int id)
        {
            return _context.Terms.Any(e => e.TermID == id);
        }
    }
}

Views/Terms/Create.cshtml
@model Clinic.Models.Terms

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Terms</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <input asp-for="Category" class="form-control" />
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Priority" /> @Html.DisplayNameFor(model => model.Priority)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DoctorId" class="control-label"></label>
                <select asp-for="DoctorId" class="form-control" asp-items="ViewBag.DoctorId">
                    <option value="">Select</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Terms/Delete.cshtml
@model Clinic.Models.Terms

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Terms</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class="col-sm-10">
            @if (Model.DoctorId != null)
            {
                <a asp-controller="Doctors" asp-action="Details" asp-route-id="@Model.DoctorId">@Html.DisplayFor(model => model.Doctor.FullName)</a>
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Patients)
        </dt>
        <dd>
            @foreach (var patient in Model.Patients)
            {
                <a asp-controller="Patients" asp-action="Details" asp-route-id="@patient.PatientID">
                    @patient.Patient.FullName
                </a> <br />
            }
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TermID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Terms/Details.cshtml
@model Clinic.Models.Terms

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Terms</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Doctor)
        </dt>
        <dd class="col-sm-10">
            @if (Model.DoctorId != null)
            {
                <a asp-controller="Doctors" asp-action="Details" asp-route-id="@Model.DoctorId">@Html.DisplayFor(model => model.Doctor.FullName)</a>
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Patients)
        </dt>
        <dd>
            @foreach (var patient in Model.Patients)
            {
                <a asp-controller="Patients" asp-action="Details" asp-route-id="@patient.PatientID">
                    @patient.Patient.FullName
                </a> <br />
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TermID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Terms/Edit.cshtml
@model Clinic.ViewModels.TermPatientEditViewModel


@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Terms</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Term.TermID" />
            <div class="form-group">
                <label asp-for="Term.Category" class="control-label"></label>
                <input asp-for="Term.Category" class="form-control" />
                <span asp-validation-for="Term.Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Term.Date" class="control-label"></label>
                <input asp-for="Term.Date" class="form-control" />
                <span asp-validation-for="Term.Date" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Term.Priority" /> @Html.DisplayNameFor(model => model.Term.Priority)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Term.DoctorId" class="control-label"></label>
                <select asp-for="Term.DoctorId" class="form-control" asp-items="ViewBag.DoctorId">
                    <option value="">Select</option>
                </select>
                <span asp-validation-for="Term.DoctorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Patients</label>
                <select asp-for="SelectedPatients" class="form-control js-example-basic-multiple"
                        asp-items="Model.PatientList"> </select>
                <span asp-validation-for="SelectedPatients" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
$(document).ready(function () {
$("#SelectedPatients").select2();
});
    </script>

}

Views/Terms/Index.cshtml
@model Clinic.ViewModels.TermPriorityViewModel
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-controller="Terms" asp-action="Index" method="get">
    <p>
        <select asp-for="TermPriority" asp-items="Model.Priorities">
            <option value="">All</option>
        </select>
        Category: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Terms[0].Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Terms[0].Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Terms[0].Priority)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Terms[0].Doctor)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Terms)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Priority)
                </td>
                <td>
                    @if (item.DoctorId != null)
                    {
                        <a asp-controller="Doctors" asp-action="Details" asp-route-id="@item.DoctorId"> @Html.DisplayFor(modelItem => item.Doctor.FullName)</a>
                    }
                </td>
                
                ...
                <td>
                    @foreach (var patient in item.Patients)
                    {
                        <a asp-controller="Patients" asp-action="Details" asp-route-id="@patient.PatientID"> @patient.Patient.FullName </a> <br />
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.TermID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.TermID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.TermID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>